 count_gene <- list(A=c(), B=c(), C=c(), D=c())

gen_count_patient <- function(N=10){SAMPLE(0:16000, 10)}
gen_count_patient()
p_a<-gen_count_patient()
> gen_x <- gen_count_patient(10000)
> set.seed(101)
> hist(gene_x)
 dir.create('figures', showWarnings = FALSE)
> pdf('figures/05-raw-count-hist.pdf', width=5,height=5)
> hist(log2(gene_x))
pdf('figures/05-raw-count-hist.pdf', width=5,height=5)
> hist(gen_x)
> dev.off()
> pdf('figures/05-log2-count-hist.pdf', width=5,height=5)
> hist(log2(gen_x))
> dev.off()
> pdf('figures/05-count-both-hist.pdf', width=7,height=5)
> hist(gen_x, main='raw count')
> hist(log2(gen_x), main ='log2 count')
> dev.off()
> pdf('figures/05-count-both-hist-onepage.pdf', width=7,height=5)
> par(mfrow=c(1,2))
> hist(gen_x, main='raw count')
> hist(log2(gen_x), main='log2 count')
> dev.off()
